bins:
	@for subdir in tipc_svr tipc_cli; \
		do\
			make -C $$subdir bins;\
		done
libs:
	@for subdir in tipc_svr tipc_cli; \
		do\
			make -C $$subdir libs;\
		done

clean:
	@for subdir in tipc_svr tipc_cli; \
		do\
			make -C $$subdir clean;\
		done