#Makefile

#TODO: fix LIB/EXE name to the current director name.
LIBS=
BINS=

CFLAGS+=--static -I/usr/include/lua5.1
LDFLAGS+=-lpthread -L/usr/lib/x86_64-linux-gnu/ -llua5.1

include ${PRJ_PATH}/make/public_make
